### ISSUE TITLE
Add default values for nutrient recovery in the WOFOST crop yield model

### ISSUE THREAD

**Issue by mcmancini** [mcmancini/UkWofost#22]
The fertilisation module in WOFOST requires nutrient recovery factor coefficients `N_recovery`, `P_recovery` and `K_recovery` to be defined in the agromanagement parameter provider, in addition to fertilisation rates. These are passed in the `TimedEvents` table:

```
    TimedEvents:
    -   event_signal: apply_npk
        name:  Timed N/P/K application table
        comment: All fertilizer amounts in kg/ha
        events_table:
        - 1976-04-29: {N_amount: 20., P_amount: 40., K_amount: 20., N_recovery: 0.7, P_recovery: 0.7, K_recovery: 0.7}
        - 1976-06-16: {N_amount: 20., P_amount: 10., K_amount: 20., N_recovery: 0.7, P_recovery: 0.7, K_recovery: 0.7}
    StateEvents: null
```
Without declaring these, WOFOST cannot successfully run.
As the current agromanagement template does not include these nutrient recovery factors, WOFOST will not run
